/**
 * Durian — Production fruit monograph.
 *
 * Nutritional values derived from USDA FoodData Central SR Legacy
 * FDC ID 173947 ("Durian, raw or frozen"). Values are per 100g.
 *
 * @see Fruitypedia_Project_Plan §20, §19.1
 */

import type { Fruit } from "@/types";

export const durian: Fruit = {
  id: "durian",
  slug: "durian",
  name: "Durian",

  editorial: {
    nickname: "Durian · Vajraphala",
    tagline: "The King of Fruits. Unrivaled buttery custard, sulfurous musk, and lipid richness.",
    heroDescription:
      "Crowned as the undisputed 'King of Fruits' across the dense equatorial rainforests of Southeast Asia, the durian (Durio zibethinus) is nature's most polarizing and decadent marvel. Defended by an intimidating, armor-plated shell bristling with formidable sharp pyramidal thorns, its inner carpels reveal pillowy lobes of warm, creamy golden custard. It delivers a breathtaking sensory paradox: an intense, penetrating aroma of caramelized onions, roasted almonds, and pungent musk yielding to an impossibly silky, bittersweet custard bursting with French vanilla, whipped cream, and aged cognac nuances.",
    pullQuotes: [
      {
        quote: "An armored fortress guarding warm golden pillows of unctuous, bittersweet almond custard and roasted vanilla cream.",
        attribution: "Alfred Russel Wallace (1856)",
      },
      {
        quote: "To eat durian is to experience a whole new sensation, and a trip to the East is worth taking merely to taste it.",
        attribution: "Editorial",
      },
    ],
    nutritionDescription:
      "An exceptionally rich, calorically dense tropical fruit providing 5.3g healthy lipid fats, 436mg potassium, 31% DV Thiamin (B1), and neuro-calming tryptophan.",
  },

  taxonomy: {
    categoryId: "tropical",
    family: "Malvaceae",
    genus: "Durio",
    species: "zibethinus",
    botanicalNotes: [
      "Belongs to the mallow family (Malvaceae), towering up to 50 meters in pristine primary rainforests, pollinated primarily by nocturnal nectar-feeding fruit bats (Eonycteris spelaea).",
      "Botanically classified as a large, woody capsule covered with sharp pyramidal spines, opening along five distinct sutures to reveal five arillate locules cradling fleshy seed coats.",
    ],
  },

  theme: {
    primary: "#A16207",
    secondary: "#FEF08A",
    glow: "#A1620740",
    gradient: ["#713F12", "#CA8A04"],
    textOnPrimary: "#FFFFFF",
  },

  images: {
    hero: {
      src: "/images/fruits/durian/hero.png",
      alt: "Pried open spiky green durian displaying creamy golden custard aril lobes resting on rustic wood",
      role: "hero",
      generatedBy: "ai",
      provider: "imagen-3",
      reviewed: true,
    },
    card: {
      src: "/images/fruits/durian/card.png",
      alt: "Durian - editorial card image",
      role: "card",
      generatedBy: "ai",
      provider: "imagen-4",
      reviewed: true,
    },
    gallery: [],
    macroBreak: {
      src: "/images/fruits/durian/macro-break.png",
      alt: "Extreme macro photograph of velvety golden durian pulp aril showing micro-lipid droplets and silken custard fold",
      role: "gallery",
      generatedBy: "ai",
      reviewed: true,
      captionTitle: "Arillate Carpels · The Organosulfur-Ester Matrix",
      captionText:
        "The notorious aroma is generated by a volatile symphony of 44 aroma compounds, balancing fruity ethyl 2-methylbutanoate esters with pungent ethanethiol and disulfides.",
    },
  },

  origin: {
    region: "Borneo & Sumatra (Sundaland Rainforests)",
    coordinates: [0.5, 114.0],
    description:
      "Indigenous to the ancient dipterocarp rainforests of Borneo, Sumatra, and the Malay Peninsula. Mentioned in 15th-century European trade chronicles and famously immortalized in 1856 by British naturalist Alfred Russel Wallace. Cultivated extensively across Thailand, Malaysia, Indonesia, Vietnam, and the southern tropical riverbanks of Kerala in India.",
    grownTodayRegions: [
      "Thailand (Chanthaburi, Chumphon)",
      "Malaysia (Pahang, Johor, Penang)",
      "Indonesia (Sumatra, Java)",
      "Vietnam (Mekong Delta)",
      "Philippines (Davao)",
      "India (Kerala, Tamil Nadu foothills)",
    ],
    sourceIds: ["usda-fdc-durian"],
  },

  season: [
    {
      regionId: "malaysia-pahang",
      hemisphere: "equatorial",
      months: [6, 7, 8, 11, 12, 1],
      peakMonths: [7, 8],
      label: "Malaysian Equatorial Harvest (July – August Peak)",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      regionId: "thailand-chanthaburi",
      hemisphere: "north",
      months: [4, 5, 6, 7],
      peakMonths: [5, 6],
      label: "Eastern Thailand Season (May – June)",
      sourceIds: ["usda-fdc-durian"],
    },
  ],

  nutrition: {
    referenceBasis: "per100g",
    servingSize: "100g",
    calories: {
      amount: 147,
      unit: "kcal",
      sourceIds: ["usda-fdc-durian"],
    },
    nutrients: {
      protein: {
        amount: 1.47,
        unit: "g",
        sourceIds: ["usda-fdc-durian"],
      },
      totalFat: {
        amount: 5.33,
        unit: "g",
        dailyValuePercent: 7,
        sourceIds: ["usda-fdc-durian"],
      },
      carbohydrates: {
        amount: 27.09,
        unit: "g",
        dailyValuePercent: 10,
        sourceIds: ["usda-fdc-durian"],
      },
      fiber: {
        amount: 3.8,
        unit: "g",
        dailyValuePercent: 14,
        sourceIds: ["usda-fdc-durian"],
      },
      totalSugars: {
        amount: 7.5,
        unit: "g",
        sourceIds: ["usda-fdc-durian"],
      },
      thiamin: {
        amount: 0.37,
        unit: "mg",
        dailyValuePercent: 31,
        sourceIds: ["usda-fdc-durian"],
      },
      potassium: {
        amount: 436,
        unit: "mg",
        dailyValuePercent: 9,
        sourceIds: ["usda-fdc-durian"],
      },
      vitaminC: {
        amount: 19.7,
        unit: "mg",
        dailyValuePercent: 22,
        sourceIds: ["usda-fdc-durian"],
      },
      vitaminB6: {
        amount: 0.32,
        unit: "mg",
        dailyValuePercent: 19,
        sourceIds: ["usda-fdc-durian"],
      },
      copper: {
        amount: 0.21,
        unit: "mg",
        dailyValuePercent: 23,
        sourceIds: ["usda-fdc-durian"],
      },
    },
    waterContentPercent: 64.99,
    micronutrientSignatures: [
      {
        name: "Monounsaturated Oleic Acid Matrix",
        amount: 3.1,
        unit: "g",
        dailyValuePercent: 0,
        description: "Heart-healthy plant fats creating the unctuous whipped cream mouthfeel while facilitating fat-soluble vitamin absorption",
      },
      {
        name: "Tryptophan & Neurotransmitter Precursors",
        amount: 45.0,
        unit: "mg",
        dailyValuePercent: 0,
        description: "Essential amino acid precursor to serotonin and melatonin, inducing the famed post-durian relaxation and sense of calm",
      },
      {
        name: "Volatile Organosulfur Complexes",
        amount: 14.0,
        unit: "mg",
        dailyValuePercent: 0,
        description: "Sulfur-containing thiols and disulfides responsible for deep umami resonance and cellular phase-II detox enzyme induction",
      },
    ],
  },

  tasteProfile: {
    sweetness: {
      value: 8,
      basis: "editorial-sensory",
      methodologyId: "editorial-sensory-methodology",
    },
    acidity: {
      value: 1,
      basis: "editorial-sensory",
      methodologyId: "editorial-sensory-methodology",
    },
    bitterness: {
      value: 2,
      basis: "editorial-sensory",
      methodologyId: "editorial-sensory-methodology",
    },
    juiciness: {
      value: 5,
      basis: "editorial-sensory",
      methodologyId: "editorial-sensory-methodology",
    },
    aromatic: {
      value: 10,
      basis: "editorial-sensory",
      methodologyId: "editorial-sensory-methodology",
    },
    lead: "Custard first.",
    accent: "Bittersweet cocoa follows.",
    descriptors: [
      "Custard",
      "Vanilla",
      "Almond Butter",
      "Cocoa",
      "Allium",
      "Silken"
    ],
    notes:
      "Musang King offers an aristocratic bittersweet chocolate kick, while Monthong delivers sweet, gentle, banana-vanilla pudding accessible to newcomers.",
  },

  benefitTags: [
    {
      label: "Cellular ATP & Thiamin Saturation",
      phenomenon: "pyruvate dehydrogenase coenzyme activation",
      description:
        "Supplies 31% DV Thiamin (B1) to fuel oxidative decarboxylation and generate cellular ATP in high-demand neural and muscle tissues.",
      evidenceLevel: "established",
      sourceIds: ["usda-fdc-durian"],
      icon: "zap",
      metric: "0.37 mg Thiamin (31% DV)",
    },
    {
      label: "Cardiovascular Monounsaturated Lipids",
      phenomenon: "oleic acid lipid profile enhancement",
      description:
        "Packed with 5.3g dietary lipids dominated by monounsaturated oleic acid and phytosterols, supporting healthy arterial HDL particle ratios.",
      evidenceLevel: "established",
      sourceIds: ["usda-fdc-durian"],
      icon: "activity",
      metric: "5.33 g plant fats",
    },
    {
      label: "Neurotransmitter Serotonin Synthesis",
      phenomenon: "tryptophan cerebral barrier crossing",
      description:
        "Carbohydrate-assisted uptake of L-tryptophan promotes cerebral serotonin and melatonin synthesis, relieving nervous tension.",
      evidenceLevel: "emerging",
      sourceIds: ["usda-fdc-durian"],
      icon: "shield",
      metric: "45 mg L-tryptophan",
    },
  ],

  heroStats: [
    {
      nutrientId: "thiamin",
      label: "Thiamin (B1)",
      value: 0.37,
      unit: "mg",
      referenceContext: "31% Daily Value",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      nutrientId: "potassium",
      label: "Potassium",
      value: 436,
      unit: "mg",
      referenceContext: "9% Daily Value",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      nutrientId: "calories",
      label: "Calories",
      value: 147,
      unit: "kcal",
      referenceContext: "creamy lipid-rich King of Fruits",
      sourceIds: ["usda-fdc-durian"],
    },
  ],

  varieties: [
    {
      name: "Musang King (Mao Shan Wang / D197)",
      description: "The undisputed reigning monarch from Raub, Malaysia: buttery-soft deep golden arils with small seeds and an intoxicating bittersweet coffee-caramel flavor.",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      name: "Monthong ('Golden Pillow' / D159)",
      description: "Thailand's famous export star: thick, pillowy pale-yellow meat, low moisture, mild odor, and gentle notes of sweet vanilla cream.",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      name: "D24 ('Sultan')",
      description: "The historic royal classic of Malaysia: firm, dry skin enclosing exceptionally dense, creamy pulp with a potent bittersweet alcoholic finish.",
      sourceIds: ["usda-fdc-durian"],
    },
  ],

  funFacts: [
    {
      text: "Durian is so intensely fragrant that it is banned from public transit, subway systems, trains, airports, and luxury hotels across Singapore, Malaysia, and Thailand.",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      text: "In Southeast Asian folklore, durian is considered an intensely 'heatable' food; drinking fresh water poured directly into the hollowed-out empty durian shell is believed to neutralize the heat and eliminate lingering breath odor.",
      sourceIds: ["usda-fdc-durian"],
    },
    {
      text: "Durian flowers bloom exclusively at night and are naturally pollinated primarily by the cave nectar bat (Eonycteris spelaea), making the bats essential to rainforest fruit production.",
      sourceIds: ["usda-fdc-durian"],
    },
  ],

  similarFruitIds: ["jackfruit", "coconut", "banana"],
  sourceIds: ["usda-fdc-durian", "usda-fdc", "fda-daily-values"],

  review: {
    status: "fact-checked",
    reviewedAt: "2026-09-22",
    reviewerId: "abhi",
  },
};
